# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: fluentd-server
#   namespace: kube-system
#   labels:
#     k8s-app: fluentd-server
#     kubernetes.io/cluster-service: "true"
#     addonmanager.kubernetes.io/mode: Reconcile
# ---
# kind: ClusterRole
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: fluentd-server
#   labels:
#     k8s-app: fluentd-server
#     kubernetes.io/cluster-service: "true"
#     addonmanager.kubernetes.io/mode: Reconcile
# rules:
# - apiGroups:
#   - ""
#   resources:
#   - "namespaces"
#   - "pods"
#   verbs:
#   - "get"
#   - "watch"
#   - "list"
# ---
# kind: ClusterRoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: fluentd-server
#   labels:
#     k8s-app: fluentd-server
#     kubernetes.io/cluster-service: "true"
#     addonmanager.kubernetes.io/mode: Reconcile
# subjects:
# - kind: ServiceAccount
#   name: fluentd-server
#   namespace: kube-system
#   apiGroup: ""
# roleRef:
#   kind: ClusterRole
#   name: fluentd-server
#   apiGroup: ""

---
apiVersion: v1
kind: Service
metadata:
  name: fluentd-server
  namespace: kube-system
  labels:
    k8s-app: fluentd-server
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Flunetd"
spec:
  ports:
  - port: 24224
    protocol: TCP
    targetPort: server
  selector:
    k8s-app: fluentd-server
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-server-v2.0.4
  namespace: kube-system
  labels:
    k8s-app: fluentd-server
    version: v2.0.4
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-server
      version: v2.0.4
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: fluentd-server
        kubernetes.io/cluster-service: "true"
        version: v2.0.4
    spec:
      # serviceAccountName: fluentd-server
      containers:
      - name: fluentd-server
        image: registry.cn-hangzhou.aliyuncs.com/acur/fluentd:v1.0
        imagePullPolicy: Always
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc
        ports:
        - containerPort: 24224
          name: server
          protocol: TCP
      terminationGracePeriodSeconds: 160
      volumes:
      - name: config-volume
        configMap:
          name: fluentd-server-config-v0.1.4
      imagePullSecrets:
      - name: kube-sec

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-server-config-v0.1.4
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  fluent.conf: |-
    <source>
      @type forward
      port 24222
    </source>
    <match **>
      @type stdout
    </match>